# risk_energy.py — Core Risk Energy Calculator
# Reads from: aree_simulation_v2.csv (generated by generate_real_data.py)
# Outputs:    re_scores dict per service per timestep

import pandas as pd
import numpy as np
import networkx as nx

# ── Weights (must match generate_real_data.py) ──────────────────────────────
W1, W2, W3, W4 = 0.25, 0.35, 0.25, 0.15

# ── Business Criticality (from generate_real_data.py) ────────────────────────
BCS = {
    "frontend":          0.70,
    "checkout_service":  0.90,
    "payment_service":   0.95,
    "auth_service":      0.85,
    "cart_service":      0.65,
    "database":          0.85
}

# ── Dependency Graph (from generate_real_data.py) ────────────────────────────
def build_dependency_graph():
    G = nx.DiGraph()
    deps = {
        "checkout_service": {"payment_service": 0.95, "auth_service": 0.7,  "cart_service": 0.8},
        "payment_service":  {"auth_service": 0.9},
        "frontend":         {"checkout_service": 0.85, "cart_service": 0.7},
        "cart_service":     {"database": 0.9},
        "auth_service":     {"database": 0.85},
        "database":         {}
    }
    for svc, neighbors in deps.items():
        for dep, weight in neighbors.items():
            G.add_edge(dep, svc, weight=weight)   # dep → svc (risk flows upstream→downstream)
    return G


# ── DSS Propagation ───────────────────────────────────────────────────────────
def compute_DSS(service, re_map, G, hop_decay=0.8):
    """
    Propagate risk from upstream dependencies into this service.
    re_map: dict {service_name: RE_value (0-100)}
    """
    dss = 0.0
    for upstream in G.predecessors(service):
        weight = G[upstream][service]['weight']
        upstream_re = re_map.get(upstream, 0.0) / 100.0   # normalize to 0-1
        dss += weight * upstream_re * hop_decay
    return round(min(1.0, dss), 4)


# ── Single RE Calculation ─────────────────────────────────────────────────────
def compute_RE(OSS, TES, DSS, BCS_val,
               w1=W1, w2=W2, w3=W3, w4=W4):
    """
    RE = OSS*W1 + TES*W2 + DSS*W3 + BCS*W4
    Returns: float 0-100
    """
    re_raw = (OSS * w1) + (TES * w2) + (DSS * w3) + (BCS_val * w4)
    return round(min(100.0, re_raw * 100.0), 2)


# ── RE Evolution Formula ──────────────────────────────────────────────────────
def evolve_RE(re_prev, oss, tes, dss, intervention=False, service=None, lam=0.08):
    """
    REt = RE(t-1) + (re_raw * 12) - (I * 25) - (λ * RE(t-1))
    Mirrors generate_real_data.py formula exactly.
    """
    re_raw = (oss * W1) + (tes * W2) + (dss * W3) + (BCS.get(service, 0.75) * W4)

    if intervention and service == "auth_service":
        I = 0.35
    elif intervention and service == "payment_service":
        I = 0.25
    else:
        I = 0.0

    re_new = re_prev + (re_raw * 12) - (I * 25) - (lam * re_prev)
    re_new = max(0.0, min(100.0, re_new))

    if intervention:
        re_new = max(re_new, 8.0)   # recovery floor

    return round(re_new, 2)


# ── Load Simulation CSV and Compute RE per timestep ──────────────────────────
def load_and_compute(csv_path="aree_simulation_v2.csv"):
    """
    Reads aree_simulation_v2.csv.
    Re-computes RE using our formula to validate against generated values.
    Returns DataFrame with added computed_RE column.
    """
    df = pd.read_csv(csv_path)
    G  = build_dependency_graph()

    results = []
    re_map  = {svc: 10.0 for svc in BCS.keys()}   # starting RE

    for t, group in df.groupby("t"):
        # Snapshot of current RE for DSS propagation
        current_re_map = re_map.copy()

        for _, row in group.iterrows():
            svc = row["service"]
            dss = compute_DSS(svc, current_re_map, G)
            re  = compute_RE(row["OSS"], row["TES"], dss, BCS.get(svc, 0.75))
            re_map[svc] = re

            results.append({
                "t":            t,
                "timestamp":    row["timestamp"],
                "service":      svc,
                "OSS":          row["OSS"],
                "TES":          row["TES"],
                "DSS":          round(dss, 4),
                "BCS":          BCS.get(svc, 0.75),
                "RE":           re,
                "RE_original":  row["RE"],          # from generate_real_data.py
                "phase":        row["phase"],
                "intervention": row["intervention"]
            })

    result_df = pd.DataFrame(results)
    return result_df


# ── Summary Stats ─────────────────────────────────────────────────────────────
def summarize(df):
    print("\n" + "="*55)
    print("  RISK ENERGY SUMMARY")
    print("="*55)

    peak = df.loc[df.RE.idxmax()]
    print(f"  Peak RE     : {peak.RE:.1f}  ({peak.service} at t={peak.t})")

    post = df[df.intervention == True]
    if not post.empty:
        avg_post = post.RE.mean()
        print(f"  Avg RE post-intervention : {avg_post:.1f}")

    print("\n  Per-Service Peak RE:")
    for svc, grp in df.groupby("service"):
        print(f"    {svc:<22} peak={grp.RE.max():.1f}  avg={grp.RE.mean():.1f}")
    print("="*55)


# ── Run standalone ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    df = load_and_compute("aree_simulation_v2.csv")
    df.to_csv("re_computed.csv", index=False)
    print(f"✅ re_computed.csv saved — {len(df)} rows")
    summarize(df)
